background = #fafafa
foreground = #6c7680
cursor-color = #3199e1
selection-background = #d1d1d1
selection-foreground = #6c7680

palette = 0=#000000
palette = 1=#ea6c6d
palette = 2=#99bf4d
palette = 3=#eca944
palette = 4=#3199e1
palette = 5=#9e75c7
palette = 6=#46ba94
palette = 7=#5a6169
palette = 8=#686868
palette = 9=#f07171
palette = 10=#86b300
palette = 11=#f2ae49
palette = 12=#399ee6
palette = 13=#a37acc
palette = 14=#4cbf99
palette = 15=#2d3640
